### ISSUE TITLE
Task: Add Java FFI wrapper for VCL solution

### ISSUE THREAD

**Issue by leeduckgo** [WeBankBlockchain/WeDPR-Lab-Core#5]
Java版本的可读性比较强。

**Comment by HaoXuan40404** [comment]
https://github.com/WeBankBlockchain/WeDPR-Lab-Java-SDK
仓库已建，开发中

**Comment by qyan-dev** [comment]
@leeduckgo FFI wrappers will be provided together with Java SDK (JNI-based), which will make it easier for Java developers to use the VCL solution. 😃
