### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by Cielover** [WeBankBlockchain/WeDPR-Lab-Core#7]
Thanks for developers in this project.
When I am running `cargo run` , the terminal returned this :
`
Checking synstructure v0.12.4
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /home/yidian/.cargo/registry/src/github.com-1ecc6299db9ec823/bulletproofs-1.0.4/src/lib.rs:1:1
  |
1 | #![feature(nll)]
  | ^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /home/yidian/.cargo/registry/src/github.com-1ecc6299db9ec823/bulletproofs-1.0.4/src/lib.rs:2:1
  |
2 | #![feature(external_doc)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /home/yidian/.cargo/registry/src/github.com-1ecc6299db9ec823/bulletproofs-1.0.4/src/lib.rs:3:1
  |
3 | #![feature(try_trait)]
  | ^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0554`.
error: could not compile `bulletproofs`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
`

Is there any version requirement of Rust? I have used `rustc --version rustc 1.46.0 (04488afe3 2020-08-24) ` How do I solve it.

**Comment by jayphbee** [comment]
you should use nightly rust

**Comment by HaoXuan40404** [comment]
maybe this can solve your problem https://www.rust-lang.org/zh-CN/tools/install

**Comment by navyup** [comment]
Install nightly version and set it default.
rustup install nightly
rustup default nightly
